[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "alembic>=1.16.4",
    "oxapy",
    "python-dotenv",
    "sqlalchemy-libsql",
]

[tool.setuptools.packages.find]
where = ["app"]
